---
title: "analysis_for_Maarouf"
output: html_document
date: "2023-10-27"
author: "Carolina Monzo"
---

Read in the files and format to remove negative values and mice that failed.
```{r}
library(dplyr)
library(stringr)
library(mixOmics)
library(impute)
library(tidyr)
library(multcomp)
library(clusterProfiler)
library(enrichplot)
library(ggupset)
library(pathview)
library(ggnewscale)

# Format removing the sequencing information from Olink
first <- read.csv("../data/Q-03195_Kroef_NPX.csv", sep = ";")
first <- first %>% 
  mutate(across(where(is.character), str_trim))
first <- first[-(1:2), , drop = FALSE]
names(first) <- as.character(unlist(first[1,]))
first <- first[-(1:3), , drop = FALSE]
first <- head(first,-4)
rownames(first) <- first$Assay
first$Assay <- NULL


# Read into a proper dataframe and remove negative values and mice that failed
df <- as.data.frame(first)
df$`QC Warning` <- NULL
df$`Plate ID` <- NULL
df <- mutate_all(df, function(x) as.numeric(as.character(as.numeric(gsub(",", ".", gsub("\\.", "", x))))))
# Change negative values into NA
df <- df %>% dplyr::mutate(across(everything(), function(x){replace(x, which(x<0), NA)}))
# Remove samples Olink selected as problematic
df <- df[!(row.names(df) %in% c("TNES-AC32", "TNES-AC86", "TNES-Y512", "TNES-AE58", "TNES-AH43")),]

## Read in the metadata
metadata <- read.csv("../metadata/metadata_Maarouf.csv", sep = ";")
metadata <- metadata[!(metadata$ID %in% c("TNES-AC32", "TNES-AC86", "TNES-Y512", "TNES-AE58", "TNES-AH43")),]
# Sort the rows in df according to metadata
df <- df[match(metadata$ID, rownames(df)),]
df <- df[(row.names(df) %in% metadata$ID), ]
```

Let's check if they separate by PLS-DA
```{r}
metadata.males <- metadata[metadata$Sex == 'm',]
metadata.females <- metadata[metadata$Sex == 'f',]

df.males <- df[(row.names(df) %in% metadata.males$ID), ]
df.females <- df[(row.names(df) %in% metadata.females$ID), ]

## PLS-DA is not separating mice according to treatment

plsda.olink.m <- mixOmics::plsda(df.males, metadata.males$Treatment, ncomp = 10)
plotIndiv(plsda.olink.m, ind.names = FALSE, ellipse = TRUE, legend = TRUE)

plsda.olink.f <- mixOmics::plsda(df.females, metadata.females$Treatment, ncomp = 10)
plotIndiv(plsda.olink.f, ind.names = FALSE, ellipse = TRUE, legend = TRUE)

## PCA is not separating mice according to treatment
pca.olink.m <- mixOmics::pca(df.males)
plotIndiv(pca.olink.m, ind.names = FALSE, ellipse = TRUE, legend = TRUE,
          group = metadata.males$Treatment)

pca.olink.f <- mixOmics::pca(df.females)
plotIndiv(pca.olink.f, ind.names = FALSE, ellipse = TRUE, legend = TRUE,
          group = metadata.females$Treatment)
```
Run one way anova and tukey between groups
```{r}
get_stats <- function(combined_df){
  # Create a list to store results for each gene
  gene_results <- list()
  
  # Loop through each gene (assuming the gene names are the column names)
  for (gene_name in (2:length(colnames(combined_df))-1)) {
    print(colnames(combined_df)[gene_name])
    # Perform one-way ANOVA for "Continuous" vs "Control"
    anova_df <- aov(formula(paste(colnames(combined_df)[gene_name], " ~ Treatment")), 
                            data = combined_df)
    
    # Perform Tukey post-hoc tests for "Continuous" vs "Control"
    tukey_df <- TukeyHSD(anova_df)
    tuk <- as.data.frame(tukey_df$Treatment)
    
    
    # Calculate the fold change for each gene
    fold_change_continuous <- mean(combined_df[combined_df$Treatment == "Continuous", colnames(combined_df)[gene_name]]) / mean(combined_df[combined_df$Treatment == "Intermittent", colnames(combined_df)[gene_name]])
    #fold_change_intermittent <- mean(combined_df[combined_df$Treatment == "Intermittent", gene_name]) / mean(combined_df[combined_df$Treatment == "Control", gene_name])
    
    # Store the results in a list
    gene_results[[colnames(combined_df)[gene_name]]] <- list(
      ANOVA = summary(anova_df)[[1]][[5]][1],
      Tukey_Continuous = tuk[row.names(tuk) %in% "Intermittent-Continuous",]$`p adj`,
      #Tukey_Intermittent = tuk[row.names(tuk) %in% "Intermittent-Control",]$`p adj`,
      FoldChange_Continuous = fold_change_continuous
      #FoldChange_Intermittent = fold_change_intermittent
    )
  }
  
  gene_results <- do.call(rbind, lapply(gene_results, unlist))
  
  return(gene_results)
}

# Combine df and metadata by matching row names
combined_df <- df.males
combined_df$Treatment <- metadata.males$Treatment
stats.males <- get_stats(combined_df)

combined_df <- df.females
combined_df$Treatment <- metadata.females$Treatment
stats.females <- get_stats(combined_df)

write.csv(stats.males, "../analysis/stats_males_contiInter_maarouf.csv")
write.csv(stats.females, "../analysis/stats_females_contiInter_maarouf.csv")
```

Run overrepresentation analysis
```{r}
original_gene_list <- rownames(stats.females)
sig_genes_females <- c('Clmp', 'Tgfb1', 'Rgma', 'Adam23', 'Wfikkn2', 'Fas', 'Erbb4', 'Il23r',
       'Dll1', 'Tnfrsf12a', 'Fstl3', 'Eda2r')
sig_genes_males <- c('Notch3', 'Cntn1', 'Gfra1', 'Ccl3', 'Il10', 'Dctn2', 'Ntf3')

go_enrich_females <- enrichGO(gene = sig_genes_females,
                      universe = original_gene_list,
                      OrgDb = "org.Mm.eg.db", 
                      keyType = 'SYMBOL',
                      readable = T,
                      ont = "BP",
                      pvalueCutoff = 0.05, 
                      qvalueCutoff = 0.10)

go_enrich_males <- enrichGO(gene = sig_genes_males,
                      universe = original_gene_list,
                      OrgDb = "org.Mm.eg.db", 
                      keyType = 'SYMBOL',
                      readable = T,
                      ont = "BP",
                      pvalueCutoff = 0.05, 
                      qvalueCutoff = 0.10)
```






